/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import api.SynthesiserV2;
import back.Database;
import back.Word;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;

/**
 *
 * @author HT3rico
 */
public class DictionaryApplication extends javax.swing.JFrame {
    Database data = new Database();
    Word word= new Word() ;
    DefaultListModel<String> dListModel = new DefaultListModel<>();
    
    /**
     * Creates new form DictionaryApplication
     */
    public DictionaryApplication() {
        initComponents();
        showAll();
 
    }
    
    public void showAll() {
        dListModel.clear();
        try ( ResultSet rs = data.exeQ("SELECT word FROM Dictionary");){
            while (rs.next()) {
                dListModel.addElement(rs.getString("word"));
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error !!! ","Lỗi Dic 4",JOptionPane.ERROR_MESSAGE);
        }
        listWord.setModel(dListModel);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        traTu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWord = new javax.swing.JList<>();
        bClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelOut = new javax.swing.JLabel();
        loa = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        textFind = new javax.swing.JTextField();
        Tracuu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HaiCoTien_Dicitonary");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setResizable(false);

        traTu.setBackground(new java.awt.Color(102, 102, 102));
        traTu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        traTu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listWord.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listWord.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        listWord.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listWordValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listWord);

        traTu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 330, 470));

        bClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconReload.jpg"))); // NOI18N
        bClear.setToolTipText("");
        bClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        traTu.add(bClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 40, 40));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        labelOut.setBackground(new java.awt.Color(255, 255, 255));
        labelOut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelOut.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(labelOut);

        traTu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 580, 470));

        loa.setText("Phát âm");
        loa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaActionPerformed(evt);
            }
        });
        traTu.add(loa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 60, 40));

        bDel.setText("Xóa");
        bDel.setToolTipText("");
        bDel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });
        traTu.add(bDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 60, 40));

        bEdit.setText("Sửa từ");
        bEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        traTu.add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 60, 40));

        bAdd.setText("Thêm từ");
        bAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        traTu.add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 60, 40));

        textFind.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        textFind.setText("Nhập từ cần tìm");
        textFind.setToolTipText(""); // NOI18N
        textFind.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textFindCaretUpdate(evt);
            }
        });
        textFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFindMouseClicked(evt);
            }
        });
        textFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFindKeyPressed(evt);
            }
        });
        traTu.add(textFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 290, 40));

        Tracuu.setBackground(new java.awt.Color(255, 255, 255));
        Tracuu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Tracuu.setForeground(new java.awt.Color(255, 255, 204));
        Tracuu.setText("Tra cứu");
        traTu.add(Tracuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(traTu, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(traTu, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   /**
     * Thêm từ
     * @param evt 
     */
    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        // TODO add your handling code here:
        Them add = new Them();
        add.setVisible(true);
    }//GEN-LAST:event_bAddActionPerformed
    /**
     * ô tìm kiếm
     * @param evt 
     */
    private void textFindCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textFindCaretUpdate
        // TODO add your handling code here:
        dListModel.clear();
        String  sql="select * from Dictionary where word like \"" + textFind.getText() + "%"+"\"";
//       ResultSet result=null;
//        word=new Word();
        if(textFind.getText().isEmpty()){
            labelOut.setText("");
        }
        else{
            try (ResultSet result = data.exeQ(sql)) {
                while (result.next()) {
                    dListModel.addElement(result.getString("word"));
                }
                result.close();
            } 
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Lỗi trong TextFind ","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        listWord.setModel(dListModel);
        }
    }//GEN-LAST:event_textFindCaretUpdate
    /**
     * Lựa chọn mới trong ListWord
     * @param evt 
     */
    private void listWordValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listWordValueChanged
        if(!listWord.isSelectionEmpty()) {    
            word= data.getword(listWord.getSelectedValue());
            if(!word.getSpelling().isEmpty())
            labelOut.setText("<HTML>"+word.getExplain()+"</HTML>");
        }
                              
    }//GEN-LAST:event_listWordValueChanged
    /**
    * Xóa
    * @param evt 
    */
    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        // TODO add your handling code here:
        if (listWord.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ để xóa","Lỗi",JOptionPane.ERROR_MESSAGE);
        } else
        if(!word.getSpelling().isEmpty()) {
            data.delete(word.getSpelling());
            JOptionPane.showMessageDialog(null, "Đã xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            textFind.setText("");
            labelOut.setText("");
            showAll();    
        }
        else
        JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ để xóa","Lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bDelActionPerformed

    private void loaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaActionPerformed
        // TODO add your handling code here:
        if (word.getSpelling().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ ","Lỗi",JOptionPane.ERROR_MESSAGE);    
        }
        else {
            SynthesiserV2 speakOn = new SynthesiserV2();
            try {
                 speakOn.speak(word.getSpelling());     
            } 
            catch (JavaLayerException ex) {     
                System.out.println(ex.toString());
                Logger.getLogger(DictionaryApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_loaActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        Sua s = new Sua();
        if (!word.getSpelling().isEmpty())
        s.setSua(word);
        s.setVisible(true);
    }//GEN-LAST:event_bEditActionPerformed
    /**
     * Click chuột vào ô tìm kiếm
     * @param evt 
     */
    private void textFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFindMouseClicked
        // TODO add your handling code here:
        textFind.setText("");
        labelOut.setText("");
    }//GEN-LAST:event_textFindMouseClicked
    /**
     * Refresh
     * @param evt 
     */
    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        textFind.setText("");
        labelOut.setText("");
    }//GEN-LAST:event_bClearActionPerformed
    /**
     * Nhận phím Enter trong Ô tìm kiếm
     * @param evt 
     */
    private void textFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFindKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (!textFind.getText().isEmpty()) { 
                word = data.getword(textFind.getText());
                if (word.getExplain()!=null){
                    labelOut.setText("<HTML>"+word.getExplain()+"</HTML>"); 
                } 
                else labelOut.setText("Không có từ cần tìm kiếm");
            }
            else {
                labelOut.setText("");
            } 
        }
    }//GEN-LAST:event_textFindKeyPressed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tracuu;
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelOut;
    private javax.swing.JList<String> listWord;
    private javax.swing.JButton loa;
    private javax.swing.JTextField textFind;
    private javax.swing.JPanel traTu;
    // End of variables declaration//GEN-END:variables
}
