/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author pc
 */
public class DictionanryApplication extends javax.swing.JFrame {
    AddWord add = new AddWord();
    DeleteWord Del = new DeleteWord();
    /**
     * Creates new form DictionanryApplication
     * @throws java.io.FileNotFoundException
     */
    static HashMap<String, String> hashMap = new HashMap<>();
    /*
    static Dictionary dic = new Dictionary();
    */
    DefaultListModel<String> model = new DefaultListModel<>();
    public void inputFromFile() throws FileNotFoundException {
        Scanner scan = new Scanner(new File("dictionaries.txt"));
        while (scan.hasNext()) {
            String word = scan.nextLine();
            Scanner s = new Scanner(word).useDelimiter("s*\ts*");
            String target = s.next();
            String explain = s.next();
            hashMap.put(target, explain);
            /*
            Word _word = new Word(target, explain);
            dic.list.add(_word);
            */
            model.addElement(target);
            
        }
    }
    public DictionanryApplication() throws FileNotFoundException {
        initComponents();
        // Set Window center on screen
        Toolkit toolkit = this.getToolkit();
        Dimension size = toolkit.getScreenSize();
        this.setLocation(size.width/2 - this.getWidth()/2,
                size.height/2 - this.getHeight()/2);
        
        // dua word tu file vao Jlist
        this.inputFromFile();
        show_word.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enter_word = new javax.swing.JTextField();
        SearchP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        show_word = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        show_meaning = new javax.swing.JTextArea();
        Add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictinary_ver_2.0");
        setResizable(false);

        enter_word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_wordActionPerformed(evt);
            }
        });
        enter_word.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                enter_wordKeyReleased(evt);
            }
        });

        SearchP.setText("Search");
        SearchP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPActionPerformed(evt);
            }
        });

        show_word.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                show_wordValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(show_word);

        show_meaning.setColumns(20);
        show_meaning.setRows(5);
        jScrollPane2.setViewportView(show_meaning);

        Add.setText("+");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(enter_word))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enter_word, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPActionPerformed
        // TODO add your handling code here:
        SearchP.setToolTipText("Tim kiem tu ban can tra");
    }//GEN-LAST:event_SearchPActionPerformed
    /**
     * The method set Text of JTextFiled to value is selected in JList
     * @param evt 
     */
    private void show_wordValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_show_wordValueChanged
        // TODO add your handling code here:
        if (show_word.getSelectedValue() != null) {
            String word = show_word.getSelectedValue().toString();
            enter_word.setText(word);
            show_meaning.setText(hashMap.get(word));
        }
    }//GEN-LAST:event_show_wordValueChanged

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        
        this.add.setVisible(true);
        /*this.setVisible(false);*/
        
    }//GEN-LAST:event_AddActionPerformed

    private void enter_wordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter_wordKeyReleased
        // TODO add your handling code here:
        String search = enter_word.getText();
        DefaultListModel<String> model1;
        model1 = new DefaultListModel<>();
        hashMap.keySet().forEach((String key) -> {
            int check = key.indexOf(search);
            if (check == 0) {
                model1.addElement(key);
            }
        });
        show_word.setModel(model1);
        if (search.equals("")) {
            show_word.setModel(model);
    }//GEN-LAST:event_enter_wordKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Del.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enter_wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_wordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_wordActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionanryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionanryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionanryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionanryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DictionanryApplication().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DictionanryApplication.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton SearchP;
    private javax.swing.JTextField enter_word;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea show_meaning;
    private javax.swing.JList<String> show_word;
    // End of variables declaration//GEN-END:variables
}
